// SPDX-License-Identifier: MIT
pragma solidity ^0.8.8;

import "./PriceConverter.sol";

error FundMe__NotOwner();

/** @title A contract for crowd funding
 *  @author soliditee
 */
contract FundMe {
    using PriceConverter for uint256;

    // immutable = variable can only be assigned during construction time,
    //   and only assigned once even during construction
    //   the contract creation code generated by the compiler will modify
    //   the contract's runtime code before it is returned
    //   by replacing all references to immutables by the values assigned to the them.
    // Reference: https://ethereum.stackexchange.com/questions/82240/what-is-the-immutable-keyword-in-solidity
    address public immutable i_owner;
    // 23619 gas - non-immutable
    // 21508 gas - immutable

    // 21415 gas - constant
    // 23515 gas - non-constant
    uint256 public MINIMUM_USD = 10 * 1e18;

    address[] public funders;
    mapping(address => uint256) public addressToAmountFunded;

    AggregatorV3Interface public priceFeed;

    modifier onlyOwner() {
        // 21509 gas - require
        // 21255 gas - if + revert error
        // require(msg.sender == i_owner, "You are not the owner.");
        if (msg.sender != i_owner) {
            revert FundMe__NotOwner();
        }
        // This means execute the rest of the code
        _;
    }

    // Functions Order:
    //// constructor
    //// receive
    //// fallback
    //// external
    //// public
    //// internal
    //// private
    //// view / pure

    constructor(address priceFeedAddress) {
        i_owner = msg.sender;
        priceFeed = AggregatorV3Interface(priceFeedAddress);
    }

    // Fallback to receive() when msg.data is empty in a transaction
    receive() external payable {
        fund();
    }

    // Fallback to fallback() when msg.data is not empty but cannot be mapped to an actual function
    fallback() external payable {
        fund();
    }

    // payable = this function can send and receive funds
    /** */
    function fund() public payable {
        // If this "require" condition is not satisfied, the transaction is reverted
        // "Revert" means to undo any action before and send the remaining gas back
        // 1e18 = 1 * 10^18 Wei = 1 Ether
        // require(getConversionRate(msg.value) >= MINIMUM_USD, "Not enough Ether");
        require(
            msg.value.getConversionRate(priceFeed) > MINIMUM_USD,
            "Please send more than 10 USD worth of Ether"
        );
        funders.push(msg.sender);
        addressToAmountFunded[msg.sender] += msg.value;
    }

    function withdraw() public onlyOwner {
        // Reset the mapping that tracks funders and their amount
        for (
            uint256 funderIndex = 0;
            funderIndex < funders.length;
            funderIndex++
        ) {
            address funderAddress = funders[funderIndex];
            addressToAmountFunded[funderAddress] = 0;
        }

        // Reset an array
        // (0) means the new array will have 0 elements to begin with
        funders = new address[](0);

        // 3 ways to withdraw the fund:
        // 1) Transfer
        // Ether can only be sent to payable addresses
        // Transfer will return error and auto-revert if fail
        // payable(msg.sender).transfer(address(this).balance);

        // 2) Send
        // Send will return bool and will not auto-revert
        // bool sendSuccess = payable(msg.sender).send(address(this).balance);
        // require(sendSuccess, "Send failed");

        // 3) Call
        // This is the most powerful, we can call any function without knowing the ABI.
        // We use "call" to create a new transaction to the sender's address and send the "value"
        // instead of making an actual function call
        // (bool callSuccess, bytes memory dataReturned)
        (bool callSuccess, ) = payable(msg.sender).call{
            value: address(this).balance
        }("");
        require(callSuccess, "Call failed");
    }
}
